TITLE = A sample paper
AUTHOR = Jakob Voß

BIBLIOGRAPHY = bibliography.bib
# CSL style for HTML
CSL=chicago-author-date-de.csl
# biblatex style for LaTeX
BIBSTYLE=authoryear

include makedoc/Makefile
